name: Deploy to cloudflare
on: [push]
jobs:
  deploy:
    name: Cloudflare deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2.2.4
      with:
        version: 7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

        cache: 'pnpm'
    - name: Install wrangler
      run: pnpm add -g wrangler
    - name: Install dependencies
      run: pnpm install
    - name: Build
      run: pnpm build
    - name: Publish
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      run: wrangler pages publish ./public --branch=${{ github.ref_name }} --project-name=beutner-dev